### ISSUE TITLE
关于训练的一些疑惑

### ISSUE THREAD

**Issue by LittleFlyingSheep** [haoxiangsnr/MetricGAN-PyTorch#1]
感谢你的代码，我看到trainer/trainer.py中在训练G时通过set_requires_grad将D的梯度固定，这样不会导致G训练无法返回梯度么？期望得到解答，谢谢。

**Comment by haoxiangsnr** [comment]
不会的，设置 set_requires_grad = False 不影响梯度传递，仅固定了参数权重。

**Comment by LittleFlyingSheep** [comment]
> 不会的，设置 set_requires_grad = False 不影响梯度传递，仅固定了参数权重。

非常感谢，我复现的过程中出现D(G(x))=1导致模型梯度消失，请问你有过这样的情况么？

**Comment by haoxiangsnr** [comment]
暂时没有遇到过。
